
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN CLICK CLOSE_PAREN COMMA CORDER CORIZQ ID NAV OPEN_PAREN SEMICOLON TEXT URLcommands    : command commands\n                   | command command : TEXT ASSIGN ID SEMICOLONcommand : NAV OPEN_PAREN URL CLOSE_PAREN SEMICOLONcommand : CLICK OPEN_PAREN TEXT CLOSE_PAREN SEMICOLONcommand : TEXT OPEN_PAREN TEXT COMMA TEXT CLOSE_PAREN SEMICOLON'
    
_lr_action_items = {'TEXT':([0,2,8,10,15,16,20,21,23,],[3,3,12,14,-3,19,-4,-5,-6,]),'NAV':([0,2,15,20,21,23,],[4,4,-3,-4,-5,-6,]),'CLICK':([0,2,15,20,21,23,],[5,5,-3,-4,-5,-6,]),'$end':([1,2,6,15,20,21,23,],[0,-2,-1,-3,-4,-5,-6,]),'ASSIGN':([3,],[7,]),'OPEN_PAREN':([3,4,5,],[8,9,10,]),'ID':([7,],[11,]),'URL':([9,],[13,]),'SEMICOLON':([11,17,18,22,],[15,20,21,23,]),'COMMA':([12,],[16,]),'CLOSE_PAREN':([13,14,19,],[17,18,22,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'commands':([0,2,],[1,6,]),'command':([0,2,],[2,2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> commands","S'",1,None,None,None),
  ('commands -> command commands','commands',2,'p_instrucciones_lista','main.py',54),
  ('commands -> command','commands',1,'p_instrucciones_lista','main.py',55),
  ('command -> TEXT ASSIGN ID SEMICOLON','command',4,'p_command_assignment','main.py',58),
  ('command -> NAV OPEN_PAREN URL CLOSE_PAREN SEMICOLON','command',5,'p_command_nav','main.py',62),
  ('command -> CLICK OPEN_PAREN TEXT CLOSE_PAREN SEMICOLON','command',5,'p_command_click','main.py',68),
  ('command -> TEXT OPEN_PAREN TEXT COMMA TEXT CLOSE_PAREN SEMICOLON','command',7,'p_command_text','main.py',74),
]
